"""
Download PSGC-derived municipality/barangay tables (Philippines GIS shapefiles,
altcoder/*, OCHA-derived) and emit static/generated/address_psgc_negros.generated.js

Keeps ONLY Negros Oriental (704600000) + Negros Occidental (604500000).
At runtime, static/addresses.js adds default "Purok 1".."Purok N" per barangay and optional named lists (ADDRESS_PUROK_OVERRIDES); PSGC has no purok layer.

Requires: Python 3.9+, network access to GitHub raw.
"""
from __future__ import annotations

import csv
import io
import json
import pathlib
import sys
import textwrap
import urllib.request


ADM3_URL = (
    "https://raw.githubusercontent.com/altcoder/philippines-psgc-shapefiles/"
    "master/dist/PH_Adm3_MuniCities.csv"
)
ADM4_URL = (
    "https://raw.githubusercontent.com/altcoder/philippines-psgc-shapefiles/"
    "master/dist/PH_Adm4_BgySubMuns.csv"
)
TARGET_ADM2 = frozenset({"604500000", "704600000"})


def _fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "geo-smart-ci-build/1"})
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read()


def main() -> int:
    root = pathlib.Path(__file__).resolve().parents[1]
    out_js = root / "static" / "generated" / "address_psgc_negros.generated.js"
    out_js.parent.mkdir(parents=True, exist_ok=True)

    print("Fetching Adm3…")
    adm3_raw = _fetch(ADM3_URL).decode("utf-8", errors="replace")
    mun_by_code: dict[str, tuple[str, str]] = {}  # adm3_psgc -> (muni_name_trim, province via adm2)
    reader3 = csv.DictReader(io.StringIO(adm3_raw))
    for row in reader3:
        adm2 = (row.get("adm2_psgc") or "").strip()
        adm3 = (row.get("adm3_psgc") or "").strip()
        if adm2 not in TARGET_ADM2 or not adm3:
            continue
        name = (row.get("adm3_en") or "").strip()
        prov = (
            "Negros Occidental"
            if adm2 == "604500000"
            else "Negros Oriental"
            if adm2 == "704600000"
            else ""
        ).strip()
        mun_by_code[adm3] = (name, prov)

    print("Fetching Adm4 (large)…")
    adm4_raw = _fetch(ADM4_URL).decode("utf-8", errors="replace")
    uniq: dict[tuple[str, str, str], bool] = {}
    geo_skip = 0
    reader4 = csv.DictReader(io.StringIO(adm4_raw))
    for row in reader4:
        adm3 = (row.get("adm3_psgc") or "").strip()
        if adm3 not in mun_by_code:
            continue
        lvl = (row.get("geo_level") or "").strip()
        # Shapefile mixes barangays and sub-municipalities; CI app handles barangay ("Bgy")
        if lvl and lvl.upper() != "BGY":
            geo_skip += 1
            continue
        mun_name, province = mun_by_code[adm3]
        bg = (row.get("adm4_en") or "").strip()
        if not bg:
            continue
        key = (province, mun_name, bg)
        uniq[key] = True

    flat = [{"province": a, "municipality": b, "barangay": c} for a, b, c in uniq.keys()]
    flat.sort(key=lambda x: (x["province"], x["municipality"], x["barangay"]))
    dumped = json.dumps(flat, ensure_ascii=False)

    prose = textwrap.dedent(
        """
        /*
         * AUTO-GENERATED by tools/build_negros_psgc_address_js.py — do not hand-edit.
         * Barangay names aligned to PSGC-derived vector tables:
         *   github.com/altcoder/philippines-psgc-shapefiles (see PSA / OCHA sources there).
         * Negros Oriental + Negros Occidental only.
         * PSGC defines barangays only; puroks are added in addresses.js (defaults + ADDRESS_PUROK_OVERRIDES).
         */
        window.__PSGC_NEGROS_BARANGAYS__ =
        """
    ).strip()

    payload = prose + dumped + ";"
    out_js.write_text(payload + "\n", encoding="utf-8")
    print(f"wrote {len(flat)} barangays -> {out_js.relative_to(root)}")
    print(f"non-Bgy geography rows skipped: {geo_skip}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
